# This is a basic workflow to help you get started with Actions

name: deploy to lambda
on:
  push:
    branches: [ master ]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: zip  package
      run: zip -r mme_lovary.zip .
    - name: default deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: lovary_daily_purchase
        zip_file: mme_lovary/mme_lovary.zip
